### ISSUE TITLE
failed to open /dev/uinput

### ISSUE THREAD

**Issue by b-coimbra** [Francesco149/stupidlayers#1]
Hey, I also got a motospeed ck62 as my first budget mech keyboard and now I'm stuck with the goddawful layer system. I was waiting for someone to create a fix for this, and I found this repo. I've been using [autokey](https://github.com/autokey/autokey) to remap my keys so far, but the zero latency from your tool is what caught my attention

I've tried to compile and run the program as instructed but I get this "failed to open /dev/uinput" error. Do you have any guesses at what might be the cause? I'd love to get a fix for this

![Stupidlayers error](https://i.imgur.com/Nk8QacJ.png)

I also tried running with other eventX files, but no luck

ps: I'm on arch linux

**Comment by Francesco149** [comment]
try `sudo modprobe uinput`

**Comment by b-coimbra** [comment]
That did the trick, thanks a lot!
the .xinitrc script also worked fine.
###### u are a genius
